# Generated by Django 6.1.1 on 2026-09-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
