# Generated by Django 6.1.1 on 2026-09-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='etiquetas',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
