# Generated by Django 6.1.1 on 2026-09-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_cuenta_etiquetas_delete_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
